### ISSUE TITLE
UnofficialOS supported systems

### ISSUE THREAD

**Issue by RetroGFX** [dag7dev/awesome-anbernic#3]
Hello..I wanted to inform u that the supported systems you have listed for us are wrong.. We support all 351, 353, and also 503,552, win 600 and powkiddy rgb20s

**Comment by dfreivald** [comment]
Pretty sure ArkOS doesn't support 35xx as well... LOL. Unless Christian has been hiding it. :D

**Comment by RetroGFX** [comment]
No he def doesn't support the 35xx.. There's only garlic and min that's it

**Comment by dag7dev** [comment]
Other than an overall enhancement on text clarity (sounding more neutral), I also just updated the list!

Thanks! 🙏
